version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: Running Unit tests
          command: |
            python3 -m unittest discover
